
dist: bionic
language: python
# Reduce the amount of downloaded data from 50MiB to 7MiB
git:
  depth: 1
matrix:
  include:
    - python: 3.9
      os: linux
      env:
        - RUN_COVERAGE=true
        - MAKE_SECP=false

    - python: 3.6
      os: linux
      env:
        - RUN_COVERAGE=false
        - MAKE_SECP=true
    - os: osx
      language: shell # 'language: python' is an error on Travis CI macOS
      addons:
        homebrew:
          packages:
            - coreutils
            - pyenv
            - gettext
      script:
        - function keep_alive() { while true; do echo -en "\a"; sleep 60; done }
        - keep_alive &
        - cd contrib/osx && ./make_osx
        - kill %keep_alive
install:
  - if [ "$MAKE_SECP" == true ];
    then
        ./contrib/make_secp;
    fi
  - pip install -r contrib/requirements/requirements-travis.txt
cache:
  - pip
script:
  - if [ "$RUN_COVERAGE" == true ];
    then
        coverage run -m electroncash.tests;
        coverage run -m electroncash_plugins.fusion.tests;
        coverage report --include="./electroncash*";
    else
        python -m electroncash.tests;
        python -m electroncash_plugins.fusion.tests;
    fi
